In [7]:

 # ! pip install beautifulsoup4
 # ! pip install requests
from bs4 import BeautifulSoup
import requests
import smtplib
import time
import datetime
import csv
import os

In [8]:
#Connect website
URL = 'https://www.amazon.com/Sleeve-Classic-Business-Embroidery-Tops-Proudly/dp/B0CT2R6BY6/?_encoding=UTF8&pd_rd_w=Nc81L&content-id=amzn1.sym.a6dce754-9901-41a6-a629-a32800521c61%3Aamzn1.symc.5a16118f-86f0-44cd-8e3e-6c5f82df43d0&pf_rd_p=a6dce754-9901-41a6-a629-a32800521c61&pf_rd_r=K5N4TWDGXD9EC056GWVV&pd_rd_wg=OchA8&pd_rd_r=06d51723-7d8a-45be-be25-8d46122c0359&ref_=pd_hp_d_atf_ci_mcx_mr_&th=1&psc=1'
# 1 dict
headers = {"User-Agent" : "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36",
           "Accept-Language": "en-US,en;q=0.9",
           "Referer": "https://www.google.com/"}
page = requests.get(URL, headers = headers)
soup1 = BeautifulSoup (page.content, "html.parser")
# soup2 = BeautifulSoup (soup1.prettify(), "html.parser")
title = soup1.find (id ='productTitle').get_text()
price = soup1.find (class_="a-section a-spacing-none aok-align-center aok-relative apex-core-price-identifier").get_text()
print(title)

print(price)

        Men's Long Sleeve Classic Oxford Shirt
  VND 2,632,387   VND2,632,387

In [9]:
price = price.strip()[:12]
title = title.strip()
print(title)
print(price)

Men's Long Sleeve Classic Oxford Shirt
VND 2,632,38

In [10]:
today = datetime.date.today()
print(today)

2026-06-11

In [11]:
import csv
header = ['Title', 'Price', 'Date']
data = [title, price,today]
type(data)
desktop = os.path.expanduser('~/Desktop')
filepath = os.path.join(desktop, 'AmazonProduct.csv')
#test with open(filepath, 'w', newline ='', encoding = 'UTF8') as f:
    #writer = csv.writer(f)
    #writer.writerow(header)
    #writer.writerow(data)

In [12]:
import pandas as pd
df = pd.read_csv(filepath)
df.head()

                                    Title         Price        Date
0  Men's Long Sleeve Classic Oxford Shirt  VND 2,631,73  2026-06-11
1  Men's Long Sleeve Classic Oxford Shirt  VND 2,631,73  2026-06-11
2  Men's Long Sleeve Classic Oxford Shirt  VND 2,631,73  2026-06-11
3  Men's Long Sleeve Classic Oxford Shirt  VND 2,631,73  2026-06-11

In [13]:
# test 
# with open(filepath, 'a+', newline ='', encoding = 'UTF8') as f:
    # writer = csv.writer(f)
   # writer.writerow(header)
    # writer.writerow(data)

In [14]:
def check_price():
 URL = 'https://www.amazon.com/Sleeve-Classic-Business-Embroidery-Tops-Proudly/dp/B0CT2R6BY6/?_encoding=UTF8&pd_rd_w=Nc81L&content-id=amzn1.sym.a6dce754-9901-41a6-a629-a32800521c61%3Aamzn1.symc.5a16118f-86f0-44cd-8e3e-6c5f82df43d0&pf_rd_p=a6dce754-9901-41a6-a629-a32800521c61&pf_rd_r=K5N4TWDGXD9EC056GWVV&pd_rd_wg=OchA8&pd_rd_r=06d51723-7d8a-45be-be25-8d46122c0359&ref_=pd_hp_d_atf_ci_mcx_mr_&th=1&psc=1'
 # 1 dict
 headers = {"User-Agent" : "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36",
           "Accept-Language": "en-US,en;q=0.9",
           "Referer": "https://www.google.com/"}
 page = requests.get(URL, headers = headers)
 soup1 = BeautifulSoup (page.content, "html.parser")
 # soup2 = BeautifulSoup (soup1.prettify(), "html.parser")
 title = soup1.find (id ='productTitle').get_text()
 price = soup1.find (class_="a-section a-spacing-none aok-align-center aok-relative apex-core-price-identifier").get_text()
 price = price.strip()[:12]
 title = title.strip()
 today = datetime.date.today()
 header = ['Title', 'Price', 'Date']
 data = [title, price,today]
 file_exists = os.path.exists(filepath) 
 with open(filepath, 'a+', newline ='', encoding = 'UTF8') as f:
     writer = csv.writer(f)
     if not file_exists: 
      writer.writerow(header)
     writer.writerow(data)

In [15]:
while (True):
    check_price()
    time.sleep(5)

KeyboardInterrupt:

In [16]:
import pandas as pd
df = pd.read_csv('/Users/liamnguyen/Desktop/AmazonProduct.csv')
df.head()

                                    Title         Price        Date
0  Men's Long Sleeve Classic Oxford Shirt  VND 2,631,73  2026-06-11
1  Men's Long Sleeve Classic Oxford Shirt  VND 2,631,73  2026-06-11
2  Men's Long Sleeve Classic Oxford Shirt  VND 2,631,73  2026-06-11
3  Men's Long Sleeve Classic Oxford Shirt  VND 2,631,73  2026-06-11
4  Men's Long Sleeve Classic Oxford Shirt  VND 2,632,38  2026-06-11